task:
  #task_root: "./evaluation_examples/"  # 从此目录中读取修改时间最靠后的json，作为任务列表
  task_file: "evaluation_examples/trainset_new_181.json"
  osworld_root: "evaluation_examples/examples_linux_osworld_0912"  # root of task detail json, organized by domain
  resume: False # 是否忽略已经跑出结果的task，测pass@1时可设为True

storage:
  root: "results/test_1222_0" ##runid of trainer
  
  splitter:
    output_dir: "splitted_traj"  # 基于storage.root的相对路径
    window_size: 5
    stride_size: 5
    max_images:  &max_images 5   # 最多保存的图片数量
    max_texts: &max_texts 35   # 最多保留的文本条数

model:
  ckpt_path: &default_ckpt_path "/path/to/UI-TARS-1.5-7B"
  # "/workspace/codes/verl/checkpoints/verl_osworld_grpo/test_1118_no_DA_20251119_e4zfxzsk/global_step_12/actor/huggingface" # "/path/to/UI-TARS-1.5-7B"
  # "/workspace/huggingface/dart-gui-7b"
  replicas:   2
  save_local: True # save local means save the [pt, images, msgs, reward] to volcano machine
  base_port:  8000
  host: &service_host "0.0.0.0"
  service_port: &service_port 15959
  service_endpoint: "http://localhost:15959"

  vllm_params:
    gpu_memory_utilization: 0.9
env:
  server_url: &server "http://47.93.220.59:4999"
  user_token: &token "7W7sE4pR2tY84I1oP3zX5cV9bN6mK0L"

coordinator:
  max_concurrent_envs: 20   # 最大并行启动的环境数量
  max_task_queue_size: 1000    # 全部任务循环几次
  rollout_n: &rollout_n 8    #  


runner:
  max_steps:  30
  max_images: *max_images    #在storage.splitter的同名字段中修改
  max_texts:  *max_texts    
  write_to_mysql: True     # 数据是否保存至mysql中
  rollout_n: *rollout_n
  save_img_pt: False   # 是否保存图片的pt文件

  env:
    server_url: *server
    user_token: *token
    max_retries: 3
    action_space: "pyautogui"
    screen_size: (1920, 1080)
    headless: True
    os_type: "Ubuntu"
    require_a11y_tree: False
    env_type: "desktop_env" # or remote_desktop 

  prelaunched_model:    # 分支方案，未成功获取vllm serve端口时，读取已启动的模型端口，用于测试
    base_url: "https://sv-98272fdc-4f22-4a25-ba0e-7d51a37448d3-8000-x-defau-51acffd7d9.sproxy.hd-01.alayanew.com:22443/v1"
    model: "ui_tars_1.5"
    frequency_penalty: 1
    max_tokens: 500
    temperature: 0.7
    top_p: 1
    seed: 1

  model_pool:     # vllm serve的相关参数
    timeout:  10
    retries:    5
    backoff:    2
    frequency_penalty: 1
    temperature: 1.0
    top_p: 1
    max_tokens: 500
    seed: 1
    logprobs: True
    return_tokens_as_token_ids: True
    ckpt_path: *default_ckpt_path
# mysql:
#   username: "teamx"
#   password: "${DB_PASSWORD}"
#   host: "localhost"
#   port: 5906
#   database: "TeamX_BIGAI"

mysql:
  username: "root"
  password: "${DB_PASSWORD}"
  host: "172.16.0.2"
  port: 3306
  database: "dart_database"
  # 配置信息
# DB_CONFIG = {
#     'host': '172.17.0.4',
#     'user': 'dart_rollouter',
#     'password': 'Dt8@Rx9p',
#     'database': 'dart_database',
#     'port': 3306,
#     'charset': 'utf8mb4'
# }
